name: Node CI
on: 
  release:
    types: [created]
    env:
      PUBLISH: true
  push:
    env:
      PUBLISH: false
jobs: 
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build and test
      run: |
        npm ci
        npm run build --if-present
        npm run testCI
      env:
        CI: true

  publish-npm:
    name: publish-npm
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@cpa30'
      - run: npm ci
      - run: echo "@cpa30:registry=https://registry.npmjs.org" >> .npmrc
      #- run: npm config set registry https://registry.npmjs.org/
      - run: cat .npmrc
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: secrets.NPM_PUBLISH_TOKEN

  publish-github:
    name: publish-github
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@freebld'
      - run: npm ci
      - run: echo "@freebld:registry=https://npm.pkg.github.com" >> .npmrc
      - run: cat .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: secrets.TOKEN_PUBLISH_GITHUB